apiVersion: batch/v1
kind: Job
metadata:
  name: process-item-$ITEM
  labels:
    jobgroup: pretrain
spec:
  template:
    metadata:
      name: pretrain-job
      labels:
        jobgroup: pretrain
    spec:
      containers:
      - name: c
        image: gcr.io/blueface/preprocess
        env:
          - name: DATA_DIR
            value: gs://koursaros/data/subset/
          - name: PROCESSED_DATA
            value: gs://koursaros/processed_data
          - name: "GOOGLE_APPLICATION_CREDENTIALS"
            value: "/var/run/secret/cloud.google.com/service-account.json"
        command: ["wget",
                  "https://storage.googleapis.com/koursaros/tiny/vocab/30k-clean.vocab",
                  "&&",
                  "wget",
                  "https://storage.googleapis.com/koursaros/tiny/vocab/30k-clean.model",
                  "&&",
                  "python3", "create_pretraining_data.py",
                  "--input_file=${DATA_DIR}/wiki_*$ITEM.txt.doc.train/",
                  "--output_file=${PROCESSED_DATA}/wiki_$ITEM.tf_record",
                  "--spm_model_file=30k-clean.model",
                  "--meta_data_file_path=${PROCESSED_DATA}/train_meta_data",
                  "--vocab_file=30k-clean.vocab"]
        resources:
          requests:
            memory: "2.7Gi"
            cpu: "1"
        volumeMounts:
          - name: "service-account"
            mountPath: "/var/run/secret/cloud.google.com"
      volumes:
        - name: "service-account"
          secret:
            secretName: "my-app-sa-key"
      restartPolicy: Never

